name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build backend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend

      - name: Push backend image
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:latest

      - name: Build frontend image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./front-end

      - name: Push frontend image
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:latest

      # - name: Call webhook on success
      - name: Call webhook on success
        run: |
          curl -X POST https://portainer.braed.co/api/stacks/webhooks/8164facc-4d76-41d5-8e77-a087f075c057
